### PR TITLE
Draft: Create code editor and preview tool for fornjot.

### PR DESCRIPTION
**Pull request by freylint**
This pull request aims to implement an [OpenSCAD](https://openscad.org/) like side by side editor built in the tauri(tau + wry) and nextjs(react) frameworks.

I'm particularly interested on feedback on project structure and this approach for UI building.

The idea is that it uses fj-viewer next to a basic code editor and refreshes the model as changes are made.
This code might also be able to be reused to implement the same in vscode.

NOTE: Tauri is not production software and many alternatives exist. I chose it to ease the implementation of the native side of the desktop client.
NOTE: This has potential to be an alternative windowing backend to winit, but this issue needs more investigation than I've given it.

### CODE REVIEW

**Comment by freylint** [comment]
This CI run shows the additional dependencies required by tauri.
The official documentation for this is in the [Tauri Documentation - Setting Up: (Linux)](https://tauri.studio/v1/guides/getting-started/setup/linux).

**Review by hannobraun — COMMENTED** [review]
Thank you for this pull request, @freylint!

First off, I'm going to convert this to a draft. You already say it is one in the title, but having it actually be one, makes things a bit more clear when browsing the list of open pull requests.

I think there are two separate questions here:
1. Is this a viable approach that should be investigated further?
2. Should this approach be developed within the Fornjot repository, or outside of it?

Here's my perspective on these questions.

> Is this a viable approach that should be investigated further?

Yes, absolutely. I mean, I don't have specific experience with Tauri, but it seems like a great project. And I think there are many reasons for choosing web technologies.

> Should this approach be developed within the Fornjot repository, or outside of it?

That's where I'm more skeptical. I'd be happy to merge a solution based on Tauri (or something comparable) eventually, once it's reached a stage where it's clearly useful, and clearly a better approach for Fornjot than possible alternatives.

But as the only maintainer currently, would I want to keep maintaining/developing it, if it was halfway done and work on it dried up? No, I don't think so. First, I don't have the capacity to do much work in this area anyway. The kernel-side stuff is keeping me busy for the time being. Second, my personal experience with JavaScript-based tooling has been bad, and I've stayed away from that ecosystem for many years now. (Yarn might be perfectly fine though; I wouldn't know.)

I'm also concerned about further increasing the build system complexity. That's absolutely something we can do, I just don't want to do it lightly.

---

So here are my thoughts on next steps:

- Keep investigating/developing an editor in a separate repository.
- Adapt components within this repository to support that effort (for example, moving windowing functionality out of `fj-viewer`, like I [mentioned elsewhere](https://github.com/hannobraun/Fornjot/pull/497#issuecomment-1124730756)).
- Keep evaluating the situation, regarding if and when the editor effort should be merged into Fornjot proper.

What do you think, @freylint?

**Comment by freylint** [comment]
I'm closing this as I plan to move it into its own repository and take on the burden of maintaining it.
I'll try to have a reasonable effort to make it easily upstreamable through things like 0bsd and potentially a CI script to test builds in source with fornjot.
I'm sure you'll be seeing plenty of PRs from my efforts to get it running in the browser for this!.

**Comment by hannobraun** [comment]
> I'm closing this as I plan to move it into its own repository and take on the burden of maintaining it.
> I'll try to have a reasonable effort to make it easily upstreamable through things like 0bsd and potentially a CI script to test builds in source with fornjot.
> I'm sure you'll be seeing plenty of PRs from my efforts to get it running in the browser for this!.

Sounds great, @freylint, thank you!

**Pull request closed without merging**
