### PR TITLE
Generalize export functions and make them public

### PR DESCRIPTION
**Pull request by IamTheCarl**
Exposes export functions for specific mesh formats and generalizes them to write to objects that implement Write (except for 3MF which needs the target to implement both Write and Seek).

### CODE REVIEW

**Review by hannobraun — APPROVED** [review]
Thank you, @IamTheCarl, looks good!

> except for 3MF which needs the target to implement both Write and Seek

I wonder why that is, and if that's a real requirement. Maybe it's just a weird leftover from an earlier version. Don't know!

**Comment by IamTheCarl** [comment]
I wondered that too so I gave the source code a quick peruse (I would have updated the ThreeMF library if it looked like an easy fix)

ThreeMF uses the Zip crate to [produce the 3MF file](https://github.com/hannobraun/3mf-rs/blob/main/src/write.rs#L17).
ZipWriter expects an object that is [both Write and Seek](https://docs.rs/zip/0.6.6/zip/write/struct.ZipWriter.html#method.new)
ZipWriter uses the seek functionality of the writer multiple times during the finalization process.

This isn't a big problem for me though. I can just output the 3MF to a tempfile before I send it to stdout, in the rare case that someone wants to pipe a 3MF file to stdout. The only situation I can see that being useful in is if someone wanted to automatically pipe a model into a slicer without an intermediate file to clean up later, which is actually something I can see myself doing.

**Comment by hannobraun** [comment]
That makes sense. Thank you for looking into it!

> This isn't a big problem for me though. I can just output the 3MF to a tempfile before I send it to stdout, in the rare case that someone wants to pipe a 3MF file to stdout. The only situation I can see that being useful in is if someone wanted to automatically pipe a model into a slicer without an intermediate file to clean up later, which is actually something I can see myself doing.

You actually don't need to go through a file. You can use [`Cursor`](https://doc.rust-lang.org/std/io/struct.Cursor.html) to do everything in-memory.

**Comment by IamTheCarl** [comment]
I did consider that but my concern is how much memory do I need? I'm probably being paranoid (thanks to my embedded background) but a spooled temp file is the best of both worlds and easy to use: https://docs.rs/tempfile/3.10.1/tempfile/struct.SpooledTempFile.html

**Comment by hannobraun** [comment]
Ah, okay. I just mentioned it in case you're not aware. `SpooledTempFile` seems like a safe bet.

**Pull request merged**
