### PR TITLE
Model recompile on windows and MacOS

### PR DESCRIPTION
**Pull request by Bandsberg**
Changes recompile to 'save file event'. 

Solves some of the issues related to #12, as the model recompiles and reloades on Win10 but only recompiles on MacOS.
The issue of reloading model on MacOS does not appear to be related monitoring of/watching for changes to model files.

### CODE REVIEW

**Comment by Bandsberg** [comment]
Also added Debug settings for codeLLDB VSCode plugin. Maybe that should either be removed or added to VScode as a suggested plugin?

**Review by hannobraun — APPROVED** [review]
Thank you, @Bandsberg, looks great! I also just tested this on my machine, and can confirm that it still works on Linux.

There's one problem: Two rebuilds are triggered for the same modification. The second rebuild barely takes any time though, so it's only a minor annoyance. And that it works on more platforms is more important anyway.

I'm going to merge this and will open a separate issue for the multiple-rebuilds problem.

**Comment by hannobraun** [comment]
> Also added Debug settings for codeLLDB VSCode extension. Maybe that should either be removed or added to VScode as a suggested extension?

Okay, as usual I forgot to reply to something.

I'm not using a debugger right now, but I'm fine with merging configuration that is used by regular contributors, as long as it's not too disruptive otherwise.

By "suggested extension", do you mean [Recommended Extensions](https://code.visualstudio.com/docs/editor/extension-marketplace#_recommended-extensions)? I haven't used this feature before, so I'm not sure what to do here. Would that mean that every VS code user would get a pop-up about this extension, or something? If so, I don't think this is necessary.

**Comment by Bandsberg** [comment]
> By "suggested extension", do you mean [Recommended Extensions](https://code.visualstudio.com/docs/editor/extension-marketplace#_recommended-extensions)? I haven't used this feature before, so I'm not sure what to do here. Would that mean that every VS code user would get a pop-up about this extension, or something? If so, I don't think this is necessary.

I do and yes there would be a pop-up. Roger that 😄

**Pull request merged**
