### PR TITLE
build: add `rust-toolchain.toml` configuration file

### PR DESCRIPTION
**Pull request by hendrikmaus**
This change-set introduces the `rust-toolchain.toml` file to the root of the project. This file will ensure that all contributors and CI pipelines always compile the project with the same Rust version.

This file is automatically picked up by `rustup`, which is the defacto standard in the Rust ecosystem to manage the toolchain.

You can test and see the override by checking out this branch and running:

_Aside: in the example below, my system already had the toolchain installed. If that is not the case, see below._

```shell
$ rustup toolchain list
stable-x86_64-unknown-linux-gnu (default)
nightly-x86_64-unknown-linux-gnu
1.58.1-x86_64-unknown-linux-gnu (override)
```

And you happen to see `1.58.1-x86_64-unknown-linux-gnu (override)`, where `override` indicates that `rustup` read the configuration and uses the desired toolchain.

If you do not (yet) have the desired toolchain installed, the first call to build the project using `cargo` will automatically leverage `rustup` to install the toolchain. You can try by:

```shell
$ rustup uninstall 1.58.1-x86_64-unknown-linux-gnu

$ rustup toolchain list
stable-x86_64-unknown-linux-gnu (default)
nightly-x86_64-unknown-linux-gnu

$ cargo build
info: syncing channel updates for '1.58.1-x86_64-unknown-linux-gnu'
info: latest update on 2022-01-20, rust version 1.58.1 (db9d1b20b 2022-01-20)
info: downloading component 'cargo'
info: downloading component 'clippy'
info: downloading component 'rust-docs'
info: downloading component 'rust-std'
info: downloading component 'rustc'
info: downloading component 'rustfmt'
info: installing component 'cargo'
info: installing component 'clippy'
info: installing component 'rust-docs'
info: installing component 'rust-std'
info: installing component 'rustc'
info: installing component 'rustfmt'
```

### CODE REVIEW

**Review by hannobraun — APPROVED** [review]
Thank you @hendrikmaus, makes sense!

One note: I've been running into a weird and persistent Rust bug when working Fornjot (an ICE related to incremental compilation; don't have the issue at hand, sorry). It was introduced in 1.58, and the fix is currently in nightly or beta.

If I run into that again, we might need to adjust the version here, but that's an easy change.

**Comment by danieleades** [comment]
sorry to post on a dead PR, but can I ask why Fornjot needs to keep all users on a common toolchain?
Is there a reason this is preferable to say, testing continuously against the latest stable compiler?

**Comment by hannobraun** [comment]
Oh wait.

> As a **user**, this file can be ignored.

(emphasis mine)

That is correct, of course. I was reading "user" as someone who clones the repository to try out the project, which is unlikely to be what you meant.

**Comment by hendrikmaus** [comment]
>  I was reading "user" as someone who clones the repository to try out the project, which is unlikely to be what you meant.

I can understand where the confusion comes from. What can we do about it? Maybe we can add a comment to the toolchain file for a start?

**Comment by hannobraun** [comment]
> Maybe we can add a comment to the toolchain file for a start?

That sounds reasonable. I've provided some context on what this version means and my thoughts on alternatives in https://github.com/hannobraun/Fornjot/issues/1420. That could serve as a basis for such a comment.

**Pull request merged**
