### PR TITLE
Refactor model import.

### PR DESCRIPTION
**Pull request by whereistejas**
Fixes: #987.

Also see, https://github.com/hannobraun/Fornjot/issues/987#issuecomment-1242987267

### CODE REVIEW

**Comment by hannobraun** [comment]
Thank you for the pull request, @whereistejas! I've taken a quick look, and think this looks reasonable. I'll do a proper review later today, or possibly tomorrow.

Please note that there are two CI failures. A Clippy warning that looks trivial to fix, and a model loading error.

**Comment by hannobraun** [comment]
Hey @whereistejas, I've taken another quick look. I still think the new API looks good, but there seems to be something fishy going on with the path. `cargo run` from the repository root fails with an error, as does trying to load any specific model (e.g. `cargo run -- -m test`).

Please let me know when this is ready for review, or if you need any help!

**Comment by hannobraun** [comment]
Hey @whereistejas, are you still interested in working on this?

**Comment by whereistejas** [comment]
hey @hannobraun sorry for late reply! yes, I totally intend to see this to the end. expect some new commits very soon! after having gone through the code more thoroughly, I don't think changing the structure of the code adds a lot of value, maybe we can just rename the methods.

**Pull request closed without merging**
